### ISSUE TITLE
Crash while navigating to sensor details

### ISSUE THREAD

**Issue by andreievg** [openmsupply/cce#1]
Had one sensor connected, for about 3 hours, when going to sensor detail, getting this:

Not sure if below is helpful

```
2017-06-29 01:49:04.992 9542-9561/? E/ReactNativeJS: Error: You need to specify name or key when calling navigate with an object as the argument. See https://reactnavigation.org/docs/navigation-actions#navigate for usage.
2017-06-29 01:49:05.032 9542-9562/? E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.common.JavascriptException: Error: You need to specify name or key when calling navigate with an object as the argument. See https://reactnavigation.org/docs/navigation-actions#navigate for usage., stack:
    navigate@44928:23
    <unknown>@47585:47
    onPress@272976:27
    onHandlerStateChange@54965:54
    _onHandlerStateChange@53745:76
    _onGestureHandlerStateChange@53129:80
    invokeGuardedCallbackImpl@5578:16
    invokeGuardedCallback@5598:35
    invokeGuardedCallbackAndCatchFirstError@5602:31
    executeDispatch@5622:43
    executeDispatchesAndReleaseTopLevel@6207:49
    forEachAccumulated@5684:64
    <unknown>@6235:26
    batchedUpdatesImpl@10721:15
    batchedUpdates@6193:31
    _receiveRootNodeIDEvent@6221:18
    receiveEvent@6244:29
    __callFunction@2018:35
    <unknown>@1839:30
    __guard@1972:14
    callFunctionReturnFlushedQueue@1838:20
    callFunctionReturnFlushedQueue@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:761)
2017-06-29 01:49:05.033 9542-9562/? E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.JavascriptException: Error: You need to specify name or key when calling navigate with an object as the argument. See https://reactnavigation.org/docs/navigation-actions#navigate for usage., stack:
    navigate@44928:23
    <unknown>@47585:47
    onPress@272976:27
    onHandlerStateChange@54965:54
    _onHandlerStateChange@53745:76
    _onGestureHandlerStateChange@53129:80
    invokeGuardedCallbackImpl@5578:16
    invokeGuardedCallback@5598:35
    invokeGuardedCallbackAndCatchFirstError@5602:31
    executeDispatch@5622:43
    executeDispatchesAndReleaseTopLevel@6207:49
    forEachAccumulated@5684:64
    <unknown>@6235:26
    batchedUpdatesImpl@10721:15
    batchedUpdates@6193:31
    _receiveRootNodeIDEvent@6221:18
    receiveEvent@6244:29
    __callFunction@2018:35
    <unknown>@1839:30
    __guard@1972:14
    callFunctionReturnFlushedQueue@1838:20
    callFunctionReturnFlushedQueue@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:761)
2017-06-29 01:49:05.035 9542-9562/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.cce, PID: 9542
    com.facebook.react.common.JavascriptException: Error: You need to specify name or key when calling navigate with an object as the argument. See https://reactnavigation.org/docs/navigation-actions#navigate for usage., stack:
    navigate@44928:23
    <unknown>@47585:47
    onPress@272976:27
    onHandlerStateChange@54965:54
    _onHandlerStateChange@53745:76
    _onGestureHandlerStateChange@53129:80
    invokeGuardedCallbackImpl@5578:16
    invokeGuardedCallback@5598:35
    invokeGuardedCallbackAndCatchFirstError@5602:31
    executeDispatch@5622:43
    executeDispatchesAndReleaseTopLevel@6207:49
    forEachAccumulated@5684:64
    <unknown>@6235:26
    batchedUpdatesImpl@10721:15
    batchedUpdates@6193:31
    _receiveRootNodeIDEvent@6221:18
    receiveEvent@6244:29
    __callFunction@2018:35
    <unknown>@1839:30
    __guard@1972:14
    callFunctionReturnFlushedQueue@1838:20
    callFunctionReturnFlushedQueue@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by joshxg** [comment]
Just fixed here, incorrect variable .. 08a524319e2f6260aad66b78d801169aa1784eda
