### ISSUE TITLE
Crash while navigating to breach configurations

### ISSUE THREAD

**Issue by andreievg** [openmsupply/cce#2]
same setup as https://github.com/openmsupply/cce/issues/1

```
2017-06-29 01:59:02.721 9898-9917/? E/ReactNativeJS: TypeError: undefined is not an object (evaluating 'breachConfiguration.byId')
    
    This error is located at:
        in TemperatureBreachSettingsScreen
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in RCTView
        in View
        in RCTView
        in View
        in ForwardRef(CardSheet)
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in PanGestureHandler
        in PanGestureHandler
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in RCTView
        in View
        in Card
        in CardContainer
        in RCTView
        in View
        in MaybeScreen
        in RCTView
        in View
        in MaybeScreenContainer
        in CardStack
        in KeyboardManager
        in SafeAreaProviderCompat
        in GestureHandlerRootView
        in GestureHandlerRootView
        in StackView
        in StackNavigator
        in SettingsStackNavigator
        in Settings
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in SceneContent
        in RCTView
        in View
        in RCTView
        in View
        in ResourceSavingScene
        in RCTView
        in View
        in ScreenContainer
        in RCTView
        in View
        in RNCSafeAreaProvider
        in SafeAreaProvider
        in SafeAreaProviderCompat
        in BottomTabView
        in BottomTabNavigator
        in MainTabNavigator
        in EnsureSingleNavigator
        in ForwardRef(BaseNavigationContainer)
        in ThemeProvider
        in ForwardRef(NavigationContainer)
        in StoreRehydrateContainer
        in DependencyContainer
        in KeepAwakeContainer
        in Provider
        in ReduxContainer
        in App
        in RCTView
        in View
        in RCTView
        in View
        in AppContainer
2017-06-29 01:59:02.733 9898-9917/? E/ReactNativeJS: TypeError: undefined is not an object (evaluating 'breachConfiguration.byId')
    
    This error is located at:
        in TemperatureBreachSettingsScreen
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in RCTView
        in View
        in RCTView
        in View
        in ForwardRef(CardSheet)
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in PanGestureHandler
        in PanGestureHandler
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in RCTView
        in View
        in Card
        in CardContainer
        in RCTView
        in View
        in MaybeScreen
        in RCTView
        in View
        in MaybeScreenContainer
        in CardStack
        in KeyboardManager
        in SafeAreaProviderCompat
        in GestureHandlerRootView
        in GestureHandlerRootView
        in StackView
        in StackNavigator
        in SettingsStackNavigator
        in Settings
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in SceneContent
        in RCTView
        in View
        in RCTView
        in View
        in ResourceSavingScene
        in RCTView
        in View
        in ScreenContainer
        in RCTView
        in View
        in RNCSafeAreaProvider
        in SafeAreaProvider
        in SafeAreaProviderCompat
        in BottomTabView
        in BottomTabNavigator
        in MainTabNavigator
        in EnsureSingleNavigator
        in ForwardRef(BaseNavigationContainer)
        in ThemeProvider
        in ForwardRef(NavigationContainer)
        in StoreRehydrateContainer
        in DependencyContainer
        in KeepAwakeContainer
        in Provider
        in ReduxContainer
        in App
        in RCTView
        in View
        in RCTView
        in View
        in AppContainer
2017-06-29 01:59:02.735 1581-1581/? D/BatteryMeterDrawable: mPluginButNotCharging is  drawing
2017-06-29 01:59:02.739 9898-9918/? E/unknown:ReactNative: TypeError: undefined is not an object (evaluating 'breachConfiguration.byId')
    
    This error is located at:
        in TemperatureBreachSettingsScreen
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in RCTView
        in View
        in RCTView
        in View
        in ForwardRef(CardSheet)
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in PanGestureHandler
        in PanGestureHandler
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in RCTView
        in View
        in Card
        in CardContainer
        in RCTView
        in View
        in MaybeScreen
        in RCTView
        in View
        in MaybeScreenContainer
        in CardStack
        in KeyboardManager
        in SafeAreaProviderCompat
        in GestureHandlerRootView
        in GestureHandlerRootView
        in StackView
        in StackNavigator
        in SettingsStackNavigator
        in Settings
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in SceneContent
        in RCTView
        in View
        in RCTView
        in View
        in ResourceSavingScene
        in RCTView
        in View
        in ScreenContainer
        in RCTView
        in View
        in RNCSafeAreaProvider
        in SafeAreaProvider
        in SafeAreaProviderCompat
        in BottomTabView
        in BottomTabNavigator
        in MainTabNavigator
        in EnsureSingleNavigator
        in ForwardRef(BaseNavigationContainer)
        in ThemeProvider
        in ForwardRef(NavigationContainer)
        in StoreRehydrateContainer
        in DependencyContainer
        in KeepAwakeContainer
        in Provider
        in ReduxContainer
        in App
        in RCTView
        in View
        in RCTView
        in View
        in AppContainer, stack:
    hotBreachConfig@249467:32
    useSelectorWithStoreAndSubscription@161437:32
    TemperatureBreachSettingsScreen@249763:48
    renderWithHooks@7750:23
    beginWork$1@10237:33
    performUnitOfWork@9854:26
    workLoopSync@9843:40
    renderRootSync@9826:20
    performSyncWorkOnRoot@9604:35
    performSyncWorkOnRoot@-1
    <unknown>@6891:33
    unstable_runWithPriority@20185:14
    flushSyncCallbackQueueImpl@6886:23
    flushSyncCallbackQueue@6876:30
    batchedUpdatesImpl@10723:103
    batchedUpdates@6193:31
    _receiveRootNodeIDEvent@6221:18
    receiveEvent@6244:29
    __callFunction@2018:35
    <unknown>@1839:30
    __guard@1972:14
    callFunctionReturnFlushedQueue@1838:20
    callFunctionReturnFlushedQueue@-1
2017-06-29 01:59:02.759 9898-9918/? E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'breachConfiguration.byId')
    
    This error is located at:
        in TemperatureBreachSettingsScreen
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in RCTView
        in View
        in RCTView
        in View
        in ForwardRef(CardSheet)
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in PanGestureHandler
        in PanGestureHandler
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in RCTView
        in View
        in Card
        in CardContainer
        in RCTView
        in View
        in MaybeScreen
        in RCTView
        in View
        in MaybeScreenContainer
        in CardStack
        in KeyboardManager
        in SafeAreaProviderCompat
        in GestureHandlerRootView
        in GestureHandlerRootView
        in StackView
        in StackNavigator
        in SettingsStackNavigator
        in Settings
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in SceneContent
        in RCTView
        in View
        in RCTView
        in View
        in ResourceSavingScene
        in RCTView
        in View
        in ScreenContainer
        in RCTView
        in View
        in RNCSafeAreaProvider
        in SafeAreaProvider
        in SafeAreaProviderCompat
        in BottomTabView
        in BottomTabNavigator
        in MainTabNavigator
        in EnsureSingleNavigator
        in ForwardRef(BaseNavigationContainer)
        in ThemeProvider
        in ForwardRef(NavigationContainer)
        in StoreRehydrateContainer
        in DependencyContainer
        in KeepAwakeContainer
        in Provider
        in ReduxContainer
        in App
        in RCTView
        in View
        in RCTView
        in View
        in AppContainer, stack:
    hotBreachConfig@249467:32
    useSelectorWithStoreAndSubscription@161437:32
    TemperatureBreachSettingsScreen@249763:48
    renderWithHooks@7750:23
    beginWork$1@10237:33
    performUnitOfWork@9854:26
    workLoopSync@9843:40
    renderRootSync@9826:20
    performSyncWorkOnRoot@9604:35
    performSyncWorkOnRoot@-1
    <unknown>@6891:33
    unstable_runWithPriority@20185:14
    flushSyncCallbackQueueImpl@6886:23
    flushSyncCallbackQueue@6876:30
    batchedUpdatesImpl@10723:103
    batchedUpdates@6193:31
    _receiveRootNodeIDEvent@6221:18
    receiveEvent@6244:29
    __callFunction@2018:35
    <unknown>@1839:30
    __guard@1972:14
    callFunctionReturnFlushedQueue@1838:20
    callFunctionReturnFlushedQueue@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:761)
2017-06-29 01:59:02.760 9898-9918/? E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'breachConfiguration.byId')
    
    This error is located at:
        in TemperatureBreachSettingsScreen
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in RCTView
        in View
        in RCTView
        in View
        in ForwardRef(CardSheet)
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in PanGestureHandler
        in PanGestureHandler
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in RCTView
        in View
        in Card
        in CardContainer
        in RCTView
        in View
        in MaybeScreen
        in RCTView
        in View
        in MaybeScreenContainer
        in CardStack
        in KeyboardManager
        in SafeAreaProviderCompat
        in GestureHandlerRootView
        in GestureHandlerRootView
        in StackView
        in StackNavigator
        in SettingsStackNavigator
        in Settings
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in SceneContent
        in RCTView
        in View
        in RCTView
        in View
        in ResourceSavingScene
        in RCTView
        in View
        in ScreenContainer
        in RCTView
        in View
        in RNCSafeAreaProvider
        in SafeAreaProvider
        in SafeAreaProviderCompat
        in BottomTabView
        in BottomTabNavigator
        in MainTabNavigator
        in EnsureSingleNavigator
        in ForwardRef(BaseNavigationContainer)
        in ThemeProvider
        in ForwardRef(NavigationContainer)
        in StoreRehydrateContainer
        in DependencyContainer
        in KeepAwakeContainer
        in Provider
        in ReduxContainer
        in App
        in RCTView
        in View
        in RCTView
        in View
        in AppContainer, stack:
    hotBreachConfig@249467:32
    useSelectorWithStoreAndSubscription@161437:32
    TemperatureBreachSettingsScreen@249763:48
    renderWithHooks@7750:23
    beginWork$1@10237:33
    performUnitOfWork@9854:26
    workLoopSync@9843:40
    renderRootSync@9826:20
    performSyncWorkOnRoot@9604:35
    performSyncWorkOnRoot@-1
    <unknown>@6891:33
    unstable_runWithPriority@20185:14
    flushSyncCallbackQueueImpl@6886:23
    flushSyncCallbackQueue@6876:30
    batchedUpdatesImpl@10723:103
    batchedUpdates@6193:31
    _receiveRootNodeIDEvent@6221:18
    receiveEvent@6244:29
    __callFunction@2018:35
    <unknown>@1839:30
    __guard@1972:14
    callFunctionReturnFlushedQueue@1838:20
    callFunctionReturnFlushedQueue@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:761)
2017-06-29 01:59:02.761 9898-9918/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.cce, PID: 9898
    com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'breachConfiguration.byId')
    
    This error is located at:
        in TemperatureBreachSettingsScreen
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in RCTView
        in View
        in RCTView
        in View
        in ForwardRef(CardSheet)
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in PanGestureHandler
        in PanGestureHandler
        in RCTView
        in View
        in AnimatedComponent
        in ForwardRef(AnimatedComponentWrapper)
        in RCTView
        in View
        in Card
        in CardContainer
        in RCTView
        in View
        in MaybeScreen
        in RCTView
        in View
        in MaybeScreenContainer
        in CardStack
        in KeyboardManager
        in SafeAreaProviderCompat
        in GestureHandlerRootView
        in GestureHandlerRootView
        in StackView
        in StackNavigator
        in SettingsStackNavigator
        in Settings
        in StaticContainer
        in StaticContainer
        in EnsureSingleNavigator
        in SceneView
        in RCTView
        in View
        in SceneContent
        in RCTView
        in View
        in RCTView
        in View
        in ResourceSavingScene
        in RCTView
        in View
        in ScreenContainer
        in RCTView
        in View
        in RNCSafeAreaProvider
        in SafeAreaProvider
        in SafeAreaProviderCompat
        in BottomTabView
        in BottomTabNavigator
        in MainTabNavigator
        in EnsureSingleNavigator
        in ForwardRef(BaseNavigationContainer)
        in ThemeProvider
        in ForwardRef(NavigationContainer)
        in StoreRehydrateContainer
        in DependencyContainer
        in KeepAwakeContainer
        in Provider
        in ReduxContainer
        in App
        in RCTView
        in View
        in RCTView
        in View
        in AppContainer, stack:
    hotBreachConfig@249467:32
    useSelectorWithStoreAndSubscription@161437:32
    TemperatureBreachSettingsScreen@249763:48
    renderWithHooks@7750:23
    beginWork$1@10237:33
    performUnitOfWork@9854:26
    workLoopSync@9843:40
    renderRootSync@9826:20
    performSyncWorkOnRoot@9604:35
    performSyncWorkOnRoot@-1
    <unknown>@6891:33
    unstable_runWithPriority@20185:14
    flushSyncCallbackQueueImpl@6886:23
    flushSyncCallbackQueue@6876:30
    batchedUpdatesImpl@10723:103
    batchedUpdates@6193:31
    _receiveRootNodeIDEvent@6221:18
    receiveEvent@6244:29
    __callFunction@2018:35
    <unknown>@1839:30
    __guard@1972:14
    callFunctionReturnFlushedQueue@1838:20
    callFunctionReturnFlushedQueue@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by joshxg** [comment]
Fixed here - 👿 devil took hold and for some reason named them with snake case https://github.com/openmsupply/cce/commit/0bf1c5e287680cb56b6012f7c10df46ad3b4c296
